In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import os
import cv2
import pandas as pd

# Load the input image
img = cv2.imread('/home/emiliano/proyecto_INAOE/GATU/corona3.jpeg', 0)

# Get the dimensions of the image
h, w = img.shape

# Calculate center of image
center_x = w // 2
center_y = h // 2

# Initialize the radar values array with 3600 samples per angle
radar_values = np.zeros((h // 2, 360))
print(h,w)

1024 1024


In [20]:
z=[]
j=[]

for angle in np.arange(0, 360, 1.0):
    for r in range(h // 2):
        x = int(np.round(center_x + r * np.sin(np.deg2rad(angle))))
        z.append(x)
        y = int(np.round(center_y + r * np.cos(np.deg2rad(angle))))
        j.append(y)


In [38]:
j=[]
l=[]

for angle in np.arange(0, 360, 1.0):
    for r in range(h // 2):
        x = int(np.round(center_x + r * np.sin(np.deg2rad(angle))))
        j.append(x)
        y = int(np.round(center_y + r * np.cos(np.deg2rad(angle))))
        l.append(y)

print(x,y,h,w)

503 1023 1024 1024


In [43]:
np.min(l)


1

In [2]:
print(h,w)

1024 1024


In [3]:
print(np.shape(radar_values))

(512, 360)


In [4]:
radar_values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
z=[]
j=[]
for angle in np.arange(0, 360, 1.0):
    for r in range(h // 2):
        x = int(np.round(center_x + r * np.sin(np.deg2rad(angle))))
        z.append(x)
        y = int(np.round(center_y + r * np.cos(np.deg2rad(angle))))
        j.append(y)
        if x < 0 or x >= w or y < 0 or y >= h:
            radar_values[r, int(angle)] = 0
        else:
            radar_values[r, int(angle)] = img[y, x]


In [6]:
print(np.shape(z))
print(512*360)


(184320,)
184320


In [7]:
np.shape(radar_values)

(512, 360)

In [8]:
avg_values = np.mean(radar_values, axis=0)

In [9]:
np.shape(avg_values)

(360,)

In [10]:
data = np.column_stack((np.arange(0, 360, 1.0), avg_values))
data

array([[  0.        ,   9.55859375],
       [  1.        ,   9.6171875 ],
       [  2.        ,  10.109375  ],
       [  3.        ,  10.75195312],
       [  4.        ,  11.06054688],
       [  5.        ,  12.12304688],
       [  6.        ,  13.265625  ],
       [  7.        ,  13.58789062],
       [  8.        ,  14.56640625],
       [  9.        ,  15.21484375],
       [ 10.        ,  16.19140625],
       [ 11.        ,  17.10351562],
       [ 12.        ,  16.09570312],
       [ 13.        ,  17.06640625],
       [ 14.        ,  18.74414062],
       [ 15.        ,  19.68554688],
       [ 16.        ,  22.28515625],
       [ 17.        ,  25.57617188],
       [ 18.        ,  27.82617188],
       [ 19.        ,  25.75390625],
       [ 20.        ,  25.84179688],
       [ 21.        ,  31.53515625],
       [ 22.        ,  30.80859375],
       [ 23.        ,  31.76953125],
       [ 24.        ,  36.66992188],
       [ 25.        ,  48.27539062],
       [ 26.        ,  52.22265625],
 

In [11]:
time_signature = (4, 4)
numerator, denominator = time_signature
print(numerator,denominator)

4 4


In [8]:
import os
import mido
import numpy as np
import matplotlib.pyplot as plt

# Load data from file
data = np.loadtxt('/home/emiliano/proyecto_INAOE/GATU/lux.csv', delimiter=',', skiprows=1)
print(data)
# Extract time and lux values
data = data[::-1]

time = data[:, 0]
lux = data[:, 1]


[[  0.      9.559]
 [  1.      9.617]
 [  2.     10.109]
 [  3.     10.752]
 [  4.     11.061]
 [  5.     12.123]
 [  6.     13.266]
 [  7.     13.588]
 [  8.     14.566]
 [  9.     15.215]
 [ 10.     16.191]
 [ 11.     17.104]
 [ 12.     16.096]
 [ 13.     17.066]
 [ 14.     18.744]
 [ 15.     19.686]
 [ 16.     22.285]
 [ 17.     25.576]
 [ 18.     27.826]
 [ 19.     25.754]
 [ 20.     25.842]
 [ 21.     31.535]
 [ 22.     30.809]
 [ 23.     31.77 ]
 [ 24.     36.67 ]
 [ 25.     48.275]
 [ 26.     52.223]
 [ 27.     54.271]
 [ 28.     57.486]
 [ 29.     55.318]
 [ 30.     50.914]
 [ 31.     51.283]
 [ 32.     46.832]
 [ 33.     45.725]
 [ 34.     43.4  ]
 [ 35.     41.947]
 [ 36.     39.934]
 [ 37.     38.762]
 [ 38.     36.463]
 [ 39.     38.066]
 [ 40.     34.416]
 [ 41.     34.709]
 [ 42.     38.186]
 [ 43.     40.254]
 [ 44.     40.197]
 [ 45.     43.582]
 [ 46.     43.061]
 [ 47.     42.646]
 [ 48.     41.518]
 [ 49.     42.035]
 [ 50.     42.35 ]
 [ 51.     40.107]
 [ 52.     4

In [9]:
data

array([[359.   ,   9.98 ],
       [358.   ,  10.447],
       [357.   ,  10.855],
       [356.   ,  13.037],
       [355.   ,  13.453],
       [354.   ,  12.195],
       [353.   ,  12.57 ],
       [352.   ,  14.076],
       [351.   ,  15.127],
       [350.   ,  16.15 ],
       [349.   ,  18.982],
       [348.   ,  22.57 ],
       [347.   ,  25.004],
       [346.   ,  31.225],
       [345.   ,  41.783],
       [344.   ,  48.045],
       [343.   ,  56.264],
       [342.   ,  62.812],
       [341.   ,  65.369],
       [340.   ,  62.678],
       [339.   ,  58.227],
       [338.   ,  54.658],
       [337.   ,  51.758],
       [336.   ,  48.41 ],
       [335.   ,  44.734],
       [334.   ,  42.74 ],
       [333.   ,  40.82 ],
       [332.   ,  39.207],
       [331.   ,  38.783],
       [330.   ,  38.957],
       [329.   ,  37.309],
       [328.   ,  33.404],
       [327.   ,  31.936],
       [326.   ,  30.355],
       [325.   ,  26.768],
       [324.   ,  24.883],
       [323.   ,  23.543],
 

In [4]:
data

array([[359.   ,   9.98 ],
       [358.   ,  10.447],
       [357.   ,  10.855],
       [356.   ,  13.037],
       [355.   ,  13.453],
       [354.   ,  12.195],
       [353.   ,  12.57 ],
       [352.   ,  14.076],
       [351.   ,  15.127],
       [350.   ,  16.15 ],
       [349.   ,  18.982],
       [348.   ,  22.57 ],
       [347.   ,  25.004],
       [346.   ,  31.225],
       [345.   ,  41.783],
       [344.   ,  48.045],
       [343.   ,  56.264],
       [342.   ,  62.812],
       [341.   ,  65.369],
       [340.   ,  62.678],
       [339.   ,  58.227],
       [338.   ,  54.658],
       [337.   ,  51.758],
       [336.   ,  48.41 ],
       [335.   ,  44.734],
       [334.   ,  42.74 ],
       [333.   ,  40.82 ],
       [332.   ,  39.207],
       [331.   ,  38.783],
       [330.   ,  38.957],
       [329.   ,  37.309],
       [328.   ,  33.404],
       [327.   ,  31.936],
       [326.   ,  30.355],
       [325.   ,  26.768],
       [324.   ,  24.883],
       [323.   ,  23.543],
 

In [9]:
import matplotlib.pyplot as plt



AttributeError: 'list' object has no attribute 'transSubfigure'